CREATE TABLE IF NOT EXISTS game_players (
  id SERIAL PRIMARY KEY,
  room_id INT NOT NULL REFERENCES game_rooms(id) ON DELETE CASCADE,
  player_name VARCHAR(50) NOT NULL,
  socket_id VARCHAR(100),
  is_host BOOLEAN NOT NULL DEFAULT FALSE,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
